name: endihub
version: '${project.version}'
main: club.endi.endihub.Endihub
api-version: '1.20'

commands:
  survival:
    description: Survival server
    aliases: [survi]
    permission: endihub.survival
    usage: /survival

  acbar:
    description: Acbar server
    aliases: [ac]
    permission: endihub.acbar
    usage: /acbar <int>

  setupserver:
    description: Setup server
    permission: endihub.setupserver
    usage: /setupserver <server>