name: endihub
version: '${project.version}'
main: club.endi.endihub.Endihub
api-version: '1.20'

commands:
  survival:
    description: Survival server
    aliases: [survi]
    permission: endihub.survival
    usage: /survival